import React, { useState, useEffect, useCallback } from 'react';
import { View, ScrollView } from 'react-native';
import { printToFileAsync } from 'expo-print';
import { shareAsync } from 'expo-sharing';
import { Screen } from '../components/Screen';
import { AppText } from '../components/AppText';
import { Card } from '../components/Card';
import { Button } from '../components/Button';
import { Icon } from '../components/Icon';
import { colors, space } from '../theme';
import { useApp } from '../context/AppContext';
import { getMedications, getVitalsHistory, triggerTwilioCall, Medication } from '../services/api';

type VitalsEntry = {
  id: string;
  type: string;
  value: string;
  unit: string;
  timestamp: string;
  status: string;
};

const esc = (s: string) =>
  String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

export default function DoctorSummaryScreen() {
  const { lang, userName, caregiverPhone } = useApp();
  const [meds, setMeds] = useState<Medication[]>([]);
  const [vitals, setVitals] = useState<VitalsEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [pdfUri, setPdfUri] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    const [m, v] = await Promise.all([getMedications(), getVitalsHistory()]);
    setMeds(m.status === 'success' ? m.medications : []);
    setVitals(v.status === 'success' ? v.history : []);
    setLoading(false);
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const buildHtml = () => {
    const now = new Date().toLocaleString(lang === 'hi' ? 'hi-IN' : 'en-IN');
    const patient = esc(userName || (lang === 'hi' ? 'मरीज़' : 'Patient'));
    const medRows = meds
      .map(
        (m) =>
          `<tr><td><b>${esc(m.name)}</b></td><td>${esc(m.dosage)}</td><td>${esc(m.timing)}</td><td>${esc(m.purpose)}</td><td style="text-align:center">${m.taken_today ? '✓' : '—'}</td></tr>`,
      )
      .join('');
    const vitalsRows = vitals
      .slice(0, 12)
      .map(
        (v) =>
          `<tr><td>${esc(v.type)}</td><td><b>${esc(v.value)} ${esc(v.unit)}</b></td><td>${esc(v.timestamp)}</td><td>${esc(v.status)}</td></tr>`,
      )
      .join('');
    const taken = meds.filter((m) => m.taken_today).length;

    return `
<html>
<head><meta charset="utf-8"><style>
  body { font-family: 'Segoe UI', 'Noto Sans Devanagari', sans-serif; color: #1a1a2e; margin: 36px; }
  h1 { font-size: 22px; margin: 0 0 2px; color: #0f766e; }
  .sub { color: #64748b; font-size: 12px; margin-bottom: 20px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #0f766e; border-bottom: 2px solid #14b8a6; padding-bottom: 4px; margin: 22px 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; background: #f0fdfa; padding: 6px 8px; border-bottom: 1px solid #99f6e4; }
  td { padding: 6px 8px; border-bottom: 1px solid #e2e8f0; }
  .banner { background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 6px; padding: 10px 14px; font-size: 12px; color: #134e4a; }
  .empty { color: #94a3b8; font-size: 12px; padding: 8px 0; }
  .foot { margin-top: 26px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 8px; }
</style></head>
<body>
  <h1>${lang === 'hi' ? 'सहारा — डॉक्टर विज़िट सारांश' : 'Sahara — Doctor Visit Summary'}</h1>
  <div class="sub">${patient} · ${esc(now)}</div>
  <div class="banner">${
    lang === 'hi'
      ? `आज की दवाएँ: ${meds.length} में से ${taken} ली गईं · हालिया वाइटल्स ${vitals.length} रीडिंग`
      : `Today's medications: ${taken} of ${meds.length} taken · ${vitals.length} recent vital readings`
  }</div>

  <h2>${lang === 'hi' ? 'रक्तचाप व वाइटल्स' : 'Vitals History'}</h2>
  ${vitalsRows ? `<table><tr><th>${lang === 'hi' ? 'प्रकार' : 'Type'}</th><th>${lang === 'hi' ? 'मान' : 'Value'}</th><th>${lang === 'hi' ? 'समय' : 'When'}</th><th>${lang === 'hi' ? 'स्थिति' : 'Status'}</th></tr>${vitalsRows}</table>` : `<div class="empty">${lang === 'hi' ? 'कोई रीडिंग दर्ज नहीं है।' : 'No readings recorded.'}</div>`}

  <h2>${lang === 'hi' ? 'वर्तमान दवाएँ' : 'Current Medications'}</h2>
  ${medRows ? `<table><tr><th>${lang === 'hi' ? 'दवा' : 'Medicine'}</th><th>${lang === 'hi' ? 'खुराक' : 'Dose'}</th><th>${lang === 'hi' ? 'समय' : 'Timing'}</th><th>${lang === 'hi' ? 'कारण' : 'Purpose'}</th><th>${lang === 'hi' ? 'आज ली' : 'Today'}</th></tr>${medRows}</table>` : `<div class="empty">${lang === 'hi' ? 'कोई दवा दर्ज नहीं है।' : 'No medications recorded.'}</div>`}

  <div class="foot">${lang === 'hi' ? 'सहारा AI स्वास्थ्य साथी द्वारा — स्वचालित सारांश, चिकित्सक सलाह नहीं।' : 'Generated by Sahara AI health companion — automated summary, not medical advice.'}</div>
</body></html>`;
  };

  const handleGenerate = async () => {
    try {
      const { uri } = await printToFileAsync({ html: buildHtml() });
      setPdfUri(uri);
    } catch (e) {
      console.warn('[pdf] printToFile failed:', e);
    }
  };

  const handleShare = async () => {
    if (!pdfUri) return;
    try {
      await shareAsync(pdfUri, { mimeType: 'application/pdf', dialogTitle: 'Sahara — Doctor Visit Summary' });
    } catch (e) {
      console.warn('[pdf] share failed:', e);
    }
  };

  return (
    <Screen
      title={lang === 'hi' ? 'डॉक्टर विज़िट सारांश' : 'Doctor Visit Summary'}
      subtitle={lang === 'hi' ? 'एक पेज PDF — डॉक्टर को दिखाने के लिए' : 'One-page PDF for your doctor'}
    >
      <ScrollView contentContainerStyle={{ gap: space.md, paddingBottom: space.xl }}>
        <Card doubleBezel tint="emerald">
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
            <Icon name="file-text" set="feather" size={22} color={colors.brand} />
            <View style={{ flex: 1 }}>
              <AppText variant="label" weight="bold" color={colors.white}>
                {lang === 'hi' ? 'वन-पेज क्लिनिकल सारांश' : 'One-page clinical summary'}
              </AppText>
              <AppText variant="small" color={colors.textMuted}>
                {lang === 'hi'
                  ? 'हालिया वाइटल्स, दवाएँ व नियमितता — डॉक्टर को देने के लिए तैयार।'
                  : 'Recent vitals, medications and adherence — ready to hand over.'}
              </AppText>
            </View>
          </View>
        </Card>

        <Card doubleBezel>
          <AppText variant="label" weight="bold" color={colors.white}>
            {lang === 'hi' ? 'शामिल जानकारी' : 'Included'}
          </AppText>
          <View style={{ marginTop: 8, gap: 6 }}>
            <AppText variant="small" color={colors.textMuted}>
              • {lang === 'hi' ? 'वाइटल्स:' : 'Vitals:'} {loading ? '…' : `${vitals.length} ${lang === 'hi' ? 'रीडिंग' : 'readings'}`}
            </AppText>
            <AppText variant="small" color={colors.textMuted}>
              • {lang === 'hi' ? 'दवाएँ:' : 'Medications:'} {loading ? '…' : `${meds.length}`}
            </AppText>
            <AppText variant="small" color={colors.textMuted}>
              • {lang === 'hi' ? 'आज की दवा नियमितता' : "Today's adherence"}
            </AppText>
          </View>
          {vitals.length === 0 && meds.length === 0 && !loading && (
            <AppText variant="small" color={colors.warn} style={{ marginTop: 8 }}>
              {lang === 'hi'
                ? 'कोई डेटा नहीं — वाइटल्स व दवाएँ पहले दर्ज करें।'
                : 'No data yet — log vitals and medications first.'}
            </AppText>
          )}
        </Card>

        <Button
          label={pdfUri ? (lang === 'hi' ? '↻ PDF दोबारा बनाएँ' : '↻ Regenerate PDF') : lang === 'hi' ? '📄 PDF बनाएँ' : '📄 Generate PDF'}
          icon="file-text"
          variant="primary"
          big
          onPress={handleGenerate}
        />

        {pdfUri && (
          <>
            <Button
              label={lang === 'hi' ? '📤 शेयर करें / सहेजें' : '📤 Share / Save'}
              icon="share-2"
              variant="outline"
              big
              onPress={handleShare}
            />
            <AppText variant="small" color={colors.textMuted} align="center" style={{ paddingHorizontal: 16 }}>
              {lang === 'hi'
                ? 'PDF तैयार है — WhatsApp से डॉक्टर या परिवार को भेज सकते हैं।'
                : 'PDF ready — share it with your doctor or family on WhatsApp.'}
            </AppText>
          </>
        )}

        <Button
          label={lang === 'hi' ? '📞 AI डॉक्टर फॉलो-अप कॉल' : '📞 AI Doctor Follow-Up Call'}
          sub={lang === 'hi' ? 'Twilio रियल वॉइस कॉल से रिपोर्ट समीक्षा' : 'Real Outbound Voice Follow-Up'}
          icon="phone-call"
          variant="outline"
          onPress={() => {
            triggerTwilioCall({
              to: caregiverPhone || '+919876543210',
              patient: userName || 'मरीज़',
              kind: 'followup',
              note: 'डॉक्टर सारांश समीक्षा व फॉलो-अप',
              lang,
            }).catch(() => {});
          }}
        />
      </ScrollView>
    </Screen>
  );
}
